# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  presentation:
    image: presentation
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    ports:
      - 5043:5043
